version: "2.0"
services:
  app:
    container_name: flask-server
    build: ./
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    depends_on:
      - db
  
  front-end:
    container_name: reactimage
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - '/src/node_modules'
    ports:
      - 3000:3000
    links:
      - app
    command: npm start

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ranking'
      MYSQL_USER: 'linh'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: