version: "2.0"
services:
  app:
    container_name: flask-server
    build: ./
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  
  front-end:
    container_name: reactimage
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - '/src/node_modules'
    ports:
      - 3000:3000
    links:
      - app
    command: npm start
